### ISSUE TITLE
Setting Price filter to the same start & end value results in an exception

### ISSUE THREAD

**Issue by heldchen** [boxalino/plugin-magento2#14]
ok: https://oursite.com/catalogsearch/result/?q=Komodo&bx_discountedPrice=3.50-5.50
exception: https://oursite.com/catalogsearch/result/?q=Komodo&bx_discountedPrice=3.50-3.50

```
1 exception(s):
Exception #0 (Exception): Notice: Trying to get property of non-object in /var/www/users/xyz/src/www/app/code/Boxalino/Intelligence/Lib/BxChooseResponse.php on line 131

Exception #0 (Exception): Notice: Trying to get property of non-object in /var/www/users/xyz/src/www/app/code/Boxalino/Intelligence/Lib/BxChooseResponse.php on line 131
#0 /var/www/users/xyz/src/www/app/code/Boxalino/Intelligence/Lib/BxChooseResponse.php(131): Magento\Framework\App\ErrorHandler->handler(8, 'Trying to get p...', '/var/www/users/...', 131, Array)
#1 /var/www/users/xyz/src/www/app/code/Boxalino/Intelligence/Helper/P13n/Adapter.php(462): com\boxalino\bxclient\v1\BxChooseResponse->getFacets('search')
#2 /var/www/users/xyz/src/www/app/code/Boxalino/Intelligence/Model/FilterList.php(78): Boxalino\Intelligence\Helper\P13n\Adapter->getFacets()
#3 /var/www/users/xyz/src/www/app/code/Boxalino/Intelligence/Model/FilterList.php(58): Boxalino\Intelligence\Model\FilterList->getBxFacets()
#4 /var/www/users/xyz/src/www/vendor/magento/module-layered-navigation/Block/Navigation.php(63): Boxalino\Intelligence\Model\FilterList->getFilters(Object(Magento\Catalog\Model\Layer\Search\Interceptor))
#5 /var/www/users/xyz/src/www/vendor/magento/framework/View/Element/AbstractBlock.php(264): Magento\LayeredNavigation\Block\Navigation->_prepareLayout()
#6 /var/www/users/xyz/src/www/vendor/magento/framework/View/Layout/Generator/Block.php(139): Magento\Framework\View\Element\AbstractBlock->setLayout(Object(Magento\Framework\View\Layout\Interceptor))
#7 /var/www/users/xyz/src/www/vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\Block->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#8 /var/www/users/xyz/src/www/vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#9 /var/www/users/xyz/src/www/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\View\Layout->generateElements()
#10 /var/www/users/xyz/src/www/var/generation/Magento/Framework/View/Layout/Interceptor.php(91): Magento\Framework\View\Layout\Interceptor->___callPlugins('generateElement...', Array, Array)
#11 /var/www/users/xyz/src/www/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#12 /var/www/users/xyz/src/www/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#13 /var/www/users/xyz/src/www/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#14 /var/www/users/xyz/src/www/vendor/magento/framework/View/Page/Config.php(197): Magento\Framework\View\Layout\Builder->build()
#15 /var/www/users/xyz/src/www/vendor/magento/framework/View/Page/Config.php(207): Magento\Framework\View\Page\Config->build()
#16 /var/www/users/xyz/src/www/vendor/magento/framework/App/View.php(170): Magento\Framework\View\Page\Config->publicBuild()
#17 /var/www/users/xyz/src/www/vendor/magento/framework/App/View.php(114): Magento\Framework\App\View->loadLayoutUpdates()
#18 /var/www/users/xyz/src/www/vendor/magento/module-catalog-search/Controller/Result/Index.php(90): Magento\Framework\App\View->loadLayout()
#19 /var/www/users/xyz/src/www/app/code/Boxalino/Intelligence/Controller/IndexController.php(67): Magento\CatalogSearch\Controller\Result\Index->execute()
#20 /var/www/users/xyz/src/www/var/generation/Boxalino/Intelligence/Controller/IndexController/Interceptor.php(24): Boxalino\Intelligence\Controller\IndexController->execute()
#21 /var/www/users/xyz/src/www/vendor/magento/framework/App/Action/Action.php(102): Boxalino\Intelligence\Controller\IndexController\Interceptor->execute()
#22 /var/www/users/xyz/src/www/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#23 /var/www/users/xyz/src/www/vendor/magento/framework/Interception/Chain/Chain.php(70): Boxalino\Intelligence\Controller\IndexController\Interceptor->___callParent('dispatch', Array)
#24 /var/www/users/xyz/src/www/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Boxalino\\Intell...', 'dispatch', Object(Boxalino\Intelligence\Controller\IndexController\Interceptor), Array, 'contextPlugin')
#25 /var/www/users/xyz/src/www/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#26 /var/www/users/xyz/src/www/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Boxalino\Intelligence\Controller\IndexController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#27 /var/www/users/xyz/src/www/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Boxalino\\Intell...', 'dispatch', Object(Boxalino\Intelligence\Controller\IndexController\Interceptor), Array, 'customer-app-ac...')
#28 /var/www/users/xyz/src/www/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#29 /var/www/users/xyz/src/www/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Boxalino\Intelligence\Controller\IndexController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#30 /var/www/users/xyz/src/www/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Boxalino\\Intell...', 'dispatch', Object(Boxalino\Intelligence\Controller\IndexController\Interceptor), Array, 'storeCheck')
#31 /var/www/users/xyz/src/www/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#32 /var/www/users/xyz/src/www/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Boxalino\Intelligence\Controller\IndexController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#33 /var/www/users/xyz/src/www/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Boxalino\\Intell...', 'dispatch', Object(Boxalino\Intelligence\Controller\IndexController\Interceptor), Array, 'tax-app-action-...')
#34 /var/www/users/xyz/src/www/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Boxalino\Intelligence\Controller\IndexController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#35 /var/www/users/xyz/src/www/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Boxalino\Intelligence\Controller\IndexController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#36 /var/www/users/xyz/src/www/var/generation/Boxalino/Intelligence/Controller/IndexController/Interceptor.php(39): Boxalino\Intelligence\Controller\IndexController\Interceptor->___callPlugins('dispatch', Array, Array)
#37 /var/www/users/xyz/src/www/vendor/magento/framework/App/FrontController.php(55): Boxalino\Intelligence\Controller\IndexController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#38 /var/www/users/xyz/src/www/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#39 /var/www/users/xyz/src/www/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#40 /var/www/users/xyz/src/www/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#41 /var/www/users/xyz/src/www/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#42 /var/www/users/xyz/src/www/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#43 /var/www/users/xyz/src/www/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#44 /var/www/users/xyz/src/www/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#45 /var/www/users/xyz/src/www/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#46 /var/www/users/xyz/src/www/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#47 /var/www/users/xyz/src/www/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#48 /var/www/users/xyz/src/www/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#49 /var/www/users/xyz/src/www/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#50 /var/www/users/xyz/src/www/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#51 /var/www/users/xyz/src/www/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#52 /var/www/users/xyz/src/www/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#53 /var/www/users/xyz/src/www/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#54 /var/www/users/xyz/src/www/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\App\Http->launch()
#55 /var/www/users/xyz/src/www/var/generation/Magento/Framework/App/Http/Interceptor.php(26): Magento\Framework\App\Http\Interceptor->___callPlugins('launch', Array, Array)
#56 /var/www/users/xyz/src/www/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http\Interceptor->launch()
#57 /var/www/users/xyz/src/www/pub/index.php(42): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#58 {main}
```

**Comment by tatsuya1** [comment]
should be fixed with the last commit.

**Comment by heldchen** [comment]
yep, will test & confirm on my dev machine once the fix for the exception is in the code

**Comment by heldchen** [comment]
confirmed fixed in the latest commits, thanks!
