### ISSUE TITLE
Exception when browsing category listing in compiled mode with Boxalino_Intelligence installed

### ISSUE THREAD

**Issue by heldchen** [boxalino/plugin-magento2#25]
```
Fatal error: Uncaught Error: Cannot instantiate abstract class Magento\Framework\App\Action\AbstractAction in /var/www/users/xxx/src/www/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:93 
Stack trace: 
#0 /var/www/users/xxx/src/www/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array) 
#1 /var/www/users/xxx/src/www/vendor/magento/framework/ObjectManager/Factory/Compiled.php(130): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...') 
#2 /var/www/users/xxx/src/www/vendor/magento/framework/ObjectManager/Factory/Compiled.php(67): Magento\Framework\ObjectManager\Factory\Compiled->get('Magento\\Framewo...') 
#3 /var/www/users/xxx/src/www/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Compiled->create('Boxalino\\Intell...', Array) 
#4 /var/www/users/xxx/src/www/vendor/magento/framework/View in /var/www/users/xxx/src/www/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93

```

**Comment by heldchen** [comment]
this is fixed in the latest commits, thanks!

**Comment by heldchen** [comment]
sorry, this is still persisting - it did not show up in the category listing due to the boxalino functions being disabled there for now. the exception still shows in the searchresults:

`Fatal error: Uncaught Error: Cannot instantiate abstract class Magento\Framework\App\Action\AbstractAction in /var/www/users/xxx/src/www/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:93 Stack trace: #0 /var/www/users/xxx/src/www/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array) #1 /var/www/users/xxx/src/www/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...', Array) #2 /var/www/users/xxx/src/www/app/code/Boxalino/Intelligence/Block/Product/BxListProducts.php(146): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...') #3 /var/www/users/xxx/src/www/app/code/Boxalino/Intelligence/Block/Product/BxListProducts.php(234): Boxalino\Intelligence\Block\Product\BxListProducts->_getProductCollection() #4 /var/www/users/xxx/src/www/vendor/magento/framework in /var/www/users/xxx/src/www/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93`

this has a low priority tho.

**Comment by heldchen** [comment]
fixed in latest commit, thanks!
